### ISSUE TITLE
Weird thing in when-00

### ISSUE THREAD

**Issue by Ptival** [UCSD-PL/kraken#22]
In https://github.com/UCSD-PL/kraken/blob/master/compiler/test/when-00/kernel.krn

Shouldn't the == 5 handler either:
- not increment the counter
- or be >= 5
  ?

**Comment by Ptival** [comment]
@d1jang What do you think?

**Comment by d1jang** [comment]
@Ptival It's a quite valid point. We can add more test cases where what you mentioned are applied.
A problem is that Kraken now supports only one logical operator, ==.
