### ISSUE TITLE
ocamldebug was changed to ocamlrun ?!

### ISSUE THREAD

**Issue by ztatlock** [UCSD-PL/kraken#23]
@d1jang @Ptival 

In https://github.com/UCSD-PL/kraken/blob/master/compiler/bin/kraken.sh "ocamldebug" was changed to "ocamlrun".

Was there a reason for this change?

I'd rather have debug, so unless someone feels strongly, I'm going to change it back.

**Comment by d1jang** [comment]
I did it so that I could see where some exceptions were thrown. 
You can change it back, and I'll add some more debug mode that uses ocamlrun instead of ocamldebug.
Can we see where an exception is thrown on ocamldebug too??

**Comment by ztatlock** [comment]
Yep, that's what debuggers are good at!  ocamlrun is not for debugging.

Reverting in this merge I'm doing.

**Comment by Ptival** [comment]
Sorry about that...
