### ISSUE TITLE
trace_impl vs. trace_spec

### ISSUE THREAD

**Issue by ztatlock** [UCSD-PL/kraken#24]
@d1jang can you explain more about trace_impl vs. trace_spec?

**Comment by ztatlock** [comment]
I think I understand:

trace_spec is used in KInvariant because we don't have the right values bound there.

However, in the actual code we need trace_impl because the let bindings give us the right values.

Does that seem right?

**Comment by d1jang** [comment]
That's the perfectly right understanding, Zach!

**Comment by ztatlock** [comment]
Cool, thanks for checking my understanding :thumbsup:
