### ISSUE TITLE
Missing handlers don't generate ValidExchange constructors

### ISSUE THREAD

**Issue by Ptival** [UCSD-PL/kraken#25]
Components who do not have any message handler don't get any ValidExchange constructor generated, thus preventing proofs from going through.

The quick & dirty fix is to add empty handlers in the kernel.krn.

**Comment by d1jang** [comment]
I'll take care of that.

**Comment by ztatlock** [comment]
You should wait.

**Comment by ztatlock** [comment]
A major change is coming down the pipeline.
