### ISSUE TITLE
Impossible to use absolute paths

### ISSUE THREAD

**Issue by Ptival** [UCSD-PL/kraken#26]
For old-quark, it would help if I could use absolute paths for components. Unfortunately, it gets compiled to:

/tmp/old-quark/client//home/ucsd/vcr/python-browser-8/input.py

**Comment by ztatlock** [comment]
after upcoming monster merge, we can fix this

basically, we'll use absolute path if provided component path begins with a "/"

**Comment by ztatlock** [comment]
@Ptival  Is this closed by #39?

**Comment by Ptival** [comment]
It is.

**Comment by Ptival** [comment]
fixed by 1d0933e.
