### ISSUE TITLE
old branches

### ISSUE THREAD

**Issue by ztatlock** [UCSD-PL/kraken#35]
@d1jang @Ptival We have a lot of old branches sitting around.

Is it OK to delete these branches?
  stateful
  ssh-proto
  components
  ifexp
  u-quark
  whenclause
  fix

They all appear to be merged into master and I don't think there's any active development on any of them...

**Comment by d1jang** [comment]
I'm okay about deleting the branches.

**Comment by Ptival** [comment]
Do it!

**Comment by ztatlock** [comment]
OK, just nuked a bunch of old branches.
